# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 120, 161, 131))
        self.groupBox.setObjectName("groupBox")
        self.input_radio_1 = QtWidgets.QRadioButton(self.groupBox)
        self.input_radio_1.setGeometry(QtCore.QRect(10, 30, 135, 28))
        self.input_radio_1.setObjectName("input_radio_1")
        self.input_radio_2 = QtWidgets.QRadioButton(self.groupBox)
        self.input_radio_2.setGeometry(QtCore.QRect(10, 60, 135, 28))
        self.input_radio_2.setObjectName("input_radio_2")
        self.input_radio_3 = QtWidgets.QRadioButton(self.groupBox)
        self.input_radio_3.setGeometry(QtCore.QRect(10, 90, 135, 28))
        self.input_radio_3.setObjectName("input_radio_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 120, 161, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.output_radio_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.output_radio_1.setGeometry(QtCore.QRect(10, 30, 135, 28))
        self.output_radio_1.setObjectName("output_radio_1")
        self.output_radio_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.output_radio_2.setGeometry(QtCore.QRect(10, 60, 135, 28))
        self.output_radio_2.setObjectName("output_radio_2")
        self.output_radio_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.output_radio_3.setGeometry(QtCore.QRect(10, 90, 135, 28))
        self.output_radio_3.setObjectName("output_radio_3")
        self.input_field = QtWidgets.QLineEdit(self.centralwidget)
        self.input_field.setGeometry(QtCore.QRect(30, 280, 161, 30))
        self.input_field.setObjectName("input_field")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(410, 280, 85, 22))
        self.result.setObjectName("result")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(134, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(320, 280, 85, 22))
        self.result_label.setObjectName("result_label")
        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(30, 320, 110, 30))
        self.calculate_button.setObjectName("calculate_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "From"))
        self.input_radio_1.setText(_translate("MainWindow", "Ce&lsius"))
        self.input_radio_2.setText(_translate("MainWindow", "Kel&vin"))
        self.input_radio_3.setText(_translate("MainWindow", "Fah&renheit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "To"))
        self.output_radio_1.setText(_translate("MainWindow", "Celsi&us"))
        self.output_radio_2.setText(_translate("MainWindow", "Kelvin"))
        self.output_radio_3.setText(_translate("MainWindow", "Fahrenheit"))
        self.result.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Temperature converter"))
        self.result_label.setText(_translate("MainWindow", "Result:"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.calculate_button.clicked.connect(self.print_message)

    def print_message(self):
        text = self.input_field.text()
        print("text: ", text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
