# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        super(UiMainWindow, self).__init__()
        self.central_widget = None

        self.title_label = None
        self.input_label = None
        self.result_label = None

        self.combo_box = None
        self.input_field = None
        self.calculate_button = None
        self.result_value = None

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(545, 335)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")

        self._setup_labels()
        self._setup_combo_box()
        self._setup_input_and_output()
        self._setup_calculate_button()

        MainWindow.setCentralWidget(self.central_widget)
        self.translate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def _setup_labels(self):
        self.title_label = QtWidgets.QLabel(self.central_widget)
        self.title_label.setGeometry(QtCore.QRect(134, 50, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title")

        self.input_label = QtWidgets.QLabel(self.central_widget)
        self.input_label.setGeometry(QtCore.QRect(30, 130, 85, 22))
        self.input_label.setObjectName("input_label")

        self.result_label = QtWidgets.QLabel(self.central_widget)
        self.result_label.setGeometry(QtCore.QRect(220, 130, 70, 22))
        self.result_label.setObjectName("result_label")

    def _setup_combo_box(self):
        self.combo_box = QtWidgets.QComboBox(self.central_widget)
        self.combo_box.setGeometry(QtCore.QRect(30, 160, 160, 30))
        self.combo_box.setObjectName("combo_box")
        self.combo_box.addItem("Celsius")
        self.combo_box.addItem("Fahrenheit")

    def _setup_input_and_output(self):
        self.input_field = QtWidgets.QLineEdit(self.central_widget)
        self.input_field.setGeometry(QtCore.QRect(30, 200, 160, 30))
        self.input_field.setObjectName("input_field")
        self.result_value = QtWidgets.QLabel(self.central_widget)
        self.result_value.setGeometry(QtCore.QRect(300, 130, 220, 22))
        self.result_value.setObjectName("result_value")

    def _setup_calculate_button(self):
        self.calculate_button = QtWidgets.QPushButton(self.central_widget)
        self.calculate_button.setGeometry(QtCore.QRect(30, 240, 110, 30))
        self.calculate_button.setObjectName("calculate_button")
        self.calculate_button.clicked.connect(self.calculate)

    def translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result_value.setText(_translate("MainWindow", "-"))
        self.title_label.setText(_translate("MainWindow", "Temperature converter"))
        self.result_label.setText(_translate("MainWindow", "Result:"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.input_label.setText(_translate("MainWindow", "From:"))

    def calculate(self):
        input_system = str(self.combo_box.currentText())
        print(input_system)
        try:
            input_value = float(self.input_field.text())
            if input_system == "Celsius":
                output_value = 9 * input_value / 5 + 32
                output_value = str(output_value) + u" \N{DEGREE SIGN}F"
            else:
                output_value = 5 * (input_value - 32) / 9
                output_value = str(output_value) + " \N{DEGREE SIGN}C"

            self.result_value.setText(str(output_value))
        except ValueError:
            self.input_field.setText("")
            self.result_value.setText("Incorrect input value!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
